export enum ErrorCode {
  // ── Validation ──────────────────────────────────────────
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  INVALID_URL_FORMAT = 'INVALID_URL_FORMAT',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_ARRAY_FORMAT = 'INVALID_ARRAY_FORMAT',
  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE',
  INVALID_JSON_BODY = 'INVALID_JSON_BODY',

  // ── Resource ────────────────────────────────────────────
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_DELETED = 'RESOURCE_DELETED',

  // ── Seeding Pipeline ────────────────────────────────────
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  INVALID_PIPELINE_STAGE = 'INVALID_PIPELINE_STAGE',
  SESSION_NOT_READY = 'SESSION_NOT_READY',
  PUBLISH_TARGET_MISSING = 'PUBLISH_TARGET_MISSING',
  DUPLICATE_BUSINESS = 'DUPLICATE_BUSINESS',
  ENRICHMENT_FAILED = 'ENRICHMENT_FAILED',
  TRANSFORMATION_FAILED = 'TRANSFORMATION_FAILED',

  // ── Database ────────────────────────────────────────────
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  DB_WRITE_FAILED = 'DB_WRITE_FAILED',
  DB_QUERY_FAILED = 'DB_QUERY_FAILED',
  DB_CAST_ERROR = 'DB_CAST_ERROR',
  DB_DUPLICATE_KEY = 'DB_DUPLICATE_KEY',
  DB_VALIDATION_ERROR = 'DB_VALIDATION_ERROR',

  // ── External Services ───────────────────────────────────
  GOOGLE_API_FAILED = 'GOOGLE_API_FAILED',
  GOOGLE_PLACE_NOT_FOUND = 'GOOGLE_PLACE_NOT_FOUND',
  PYTHON_BOT_UNREACHABLE = 'PYTHON_BOT_UNREACHABLE',
  PYTHON_BOT_FAILED = 'PYTHON_BOT_FAILED',

  // ── Auth ────────────────────────────────────────────────
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_ADMIN_PASSWORD = 'INVALID_ADMIN_PASSWORD',

  // ── Server ──────────────────────────────────────────────
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.INVALID_OBJECT_ID]: 400,
  [ErrorCode.INVALID_ENUM_VALUE]: 400,
  [ErrorCode.INVALID_DATE_FORMAT]: 400,
  [ErrorCode.INVALID_URL_FORMAT]: 400,
  [ErrorCode.INVALID_EMAIL_FORMAT]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,
  [ErrorCode.INVALID_ARRAY_FORMAT]: 400,
  [ErrorCode.VALUE_OUT_OF_RANGE]: 400,
  [ErrorCode.INVALID_JSON_BODY]: 400,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
  [ErrorCode.RESOURCE_CONFLICT]: 409,
  [ErrorCode.RESOURCE_DELETED]: 410,
  [ErrorCode.SESSION_NOT_FOUND]: 404,
  [ErrorCode.RECORD_NOT_FOUND]: 404,
  [ErrorCode.INVALID_PIPELINE_STAGE]: 422,
  [ErrorCode.SESSION_NOT_READY]: 422,
  [ErrorCode.PUBLISH_TARGET_MISSING]: 422,
  [ErrorCode.DUPLICATE_BUSINESS]: 409,
  [ErrorCode.ENRICHMENT_FAILED]: 422,
  [ErrorCode.TRANSFORMATION_FAILED]: 422,
  [ErrorCode.DB_CONNECTION_FAILED]: 503,
  [ErrorCode.DB_WRITE_FAILED]: 500,
  [ErrorCode.DB_QUERY_FAILED]: 500,
  [ErrorCode.DB_CAST_ERROR]: 400,
  [ErrorCode.DB_DUPLICATE_KEY]: 409,
  [ErrorCode.DB_VALIDATION_ERROR]: 400,
  [ErrorCode.GOOGLE_API_FAILED]: 502,
  [ErrorCode.GOOGLE_PLACE_NOT_FOUND]: 404,
  [ErrorCode.PYTHON_BOT_UNREACHABLE]: 503,
  [ErrorCode.PYTHON_BOT_FAILED]: 502,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INVALID_ADMIN_PASSWORD]: 401,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.NOT_IMPLEMENTED]: 501,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
};
